### ISSUE TITLE
Data visualisations, particularly the bar chart of visits data should be able to vary time-scale.

### ISSUE THREAD

**Issue by RogeredBacon** [TwinePlatform/twine-visitor#197]
Data Visualisations, particularly the bar chart of visits data should be able to vary time-scale.

Currently the chart displays visits over the last week. It would be good to make it able to display the last month also. Ideally a user would be able to select the two dates between which the visits data would be displayed.

**Comment by astroash** [comment]
Worth checking with Sonja to see if this is a desired feature.
