### ISSUE TITLE
Change some of our copy specifically error messages away from defaults

### ISSUE THREAD

**Issue by RogeredBacon** [TwinePlatform/twine-visitor#215]
Not much work and not particularly important but I feel we could make some of our copy for error messages and such slightly more unique.

- Our team of highly trained monkeys -> Our highly talented and unusually attractive team
- ...
- ...

What do you think?

**Comment by astroash** [comment]
@RogeredBacon sounds great!

**Comment by astroash** [comment]
Many error messages are now coming from state 🎉
