### ISSUE TITLE
Mixing between gender and sex in db queries

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#245]
We mix between using the words "sex" and "gender" throughout the app. I assume we should be collecting information on gender but should double check with PO and reflect the outcome in the codebase.

Relates #210

**Comment by eliascodes** [comment]
This also left me 🤔 

FWIW the new designs use the word "Gender" on the input fields, but not sure if that came from Sonja.

**Comment by eliascodes** [comment]
Confirmed with PO that this should be gender.

**Comment by astroash** [comment]
Closing as we are migrating to a new db
