### ISSUE TITLE
Contact user by email and SMS

### ISSUE THREAD

**Issue by RogeredBacon** [TwinePlatform/twine-visitor#260]
We need a way for an admin to be able to uncheck these options for a user:
- [ ]  Check-boxes on user page

An admin also needs a way to see which users have allowed for this communication.
- [ ] Ability to sort or list users who have agreed to one or both

**Comment by astroash** [comment]
This is one of the things I brought up during scoping. Sonja said for now we’re just collecting the info but not doing anything with it :)

**Comment by RogeredBacon** [comment]
As discussed we'll leave this for another sprint when we know more about how this is going to be used. :clock10:

**Comment by astroash** [comment]
Worth bringing this back up with Sonja, as it is linked to GDPR compliance.

**Comment by astroash** [comment]
superseded by #537
