### ISSUE TITLE
Async await vs promises

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#271]
I keep chopping n changing between writing `promises` n `async await` 😅. Any preferences of what we should use moving forward or can I continue my arbitrary use of each?

**Comment by astroash** [comment]
I got no response on this so I'll just keep doing my thing... _unless prompted otherwise_

**Comment by RogeredBacon** [comment]
I've never really used async await, so I'll be doing everything in promises probably

**Comment by eliascodes** [comment]
IMO this is something that should be determined by code clarity. If a given case would be clearer and/or simpler to write using one or the other, do that. IMO default should be `async`/`await` since it seems to be becoming the defacto standard way to structure async code.
