### ISSUE TITLE
Redux 🤔

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#284]
Should we introduce redux to the project? It will avoid us calling asynchronous functions in shortlived components state, and the [messy hacks ](https://github.com/TwinePlatform/DataPower/pull/281/commits/69f19d37a94ebd54dd2eacd66f637f0d94c1e7c2) attached to this.

**Comment by eliascodes** [comment]
Yeah I was gonna raise this, then thought again, because I've already introduced quite a lot of new stuff this phase. The app isn't _so_ complicated yet as to require it. Eventually though...maybe next time round.

**Comment by astroash** [comment]
For reference when we come back to look at this, a number of issues encountered on [test-live-api](https://github.com/TwinePlatform/twine-visitor/tree/test-live-api) would be solved with redux. These were due to `setState` being called after components were unmounted, and were not solvable with the `toCancellable` util.

**Comment by eliascodes** [comment]
I'm not convinced we really know what the problem with that branch was, nor do I understand how redux would have helped even if it was what you describe.

**Comment by astroash** [comment]
superseeded by #621
