### ISSUE TITLE
Resolution and Aspect Ratio

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#286]
As we are about to hit a design phase, it would be useful to find out from Sonja how this app is likely to be displayed eg portrait or landscape on tablets, and which tablets may be used so we can check with their resolution to avoid this:

<img width="949" alt="screen shot 2018-03-20 at 16 39 59" src="https://user-images.githubusercontent.com/14337958/37661541-b98354a0-2c5d-11e8-99f7-984ed6d69228.png">

**Comment by eliascodes** [comment]
The issue in the screenshot doesn't really have anything to do with knowing orientation or resolution. The visualisations should be positioned relatively not absolutely and adhere to whatever layout system we're using.

FWIW I've been checking the design mainly on landscape iPad and iPad Pro emulator settings.

**Comment by astroash** [comment]
☝🏽 CSS 🤴
