### ISSUE TITLE
Colours for the graphs

### ISSUE THREAD

**Issue by RogeredBacon** [TwinePlatform/twine-visitor#294]
I think this is something we need to discuss and then ask Sonja what she thinks:

- What colours? Do we stick to a theme? Will a theme make differentiating between graphs confusing?
- Should colours for gender and age group graphs be the same every time?
- There can be an infinite amount of activities so should the colours be randomly generated?
- If we do randomly generate colours, should we make sure that each colour is different enough from the others to be easily recognisable?
- Should the colours for gender be the standard blue/red?
- If we don't use the blue/red standard should we actively avoid these colours in the gender graph, to minimise confusion?

**Comment by astroash** [comment]
> What colours? Do we stick to a theme? Will a theme make differentiating between graphs confusing?

Defo for us having a colour palette which is consistent across all graphs
> Should colours for gender and age group graphs be the same every time?

Yup, I was playing around doing this by having a graph config which is an array of objects, with each obj having label name and the colours that attached to it eg 
```js
[ 
  { label: 'jetskiing', 
     primaryColour : 'radBlue', 
     secondaryColour : 'sadBlue'
  } 
]
```
> There can be an `Infinite` amount of activities so should the colours be randomly generated?
> If we do randomly generate colours, should we make sure that each colour is different enough from the others to be easily recognisable?

If we have 5 colours, and labels, will the colours repeat? I think this could look nice, if we're just using labels.
> Should the colours for gender be the standard blue/red?
> If we don't use the blue/red standard should we actively avoid these colours in the gender graph, to minimise confusion?

How about using the app yellow and purple? Will also need a colour for 'prefer not to disclose'

**Comment by RogeredBacon** [comment]
- I agree a colour palette would look good, though we have to take into account the the activities pie graph uses completely different data then the gender and age ones so should be distinct along with the visits bar graph.

- Yeah the colours would repeat if there's more activites than colours. I think it will be very confusing ,even with labels, if after only 5 they repeat. What about with 15 or more activities?

- Yeah I guess we'll be using the Twine yellow and purple a lot haha
