### ISSUE TITLE
Styled Components extending/naming convention

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#295]
I wanna use `PrimaryButtonNoFill` but the width is set in `PrimaryButton`. I'm wondering if there is a convention for recurring component so that we add css properties in a set order to avoid creating very similar extended components or extending and overwriting prewritten properties or just adhoc adding props with defaults to avoid breaking things.

https://github.com/TwinePlatform/DataPower/blob/18b702c0772456e180596bb0ffb445e96424a6e1/react-backend/client/src/shared/components/form/base.js#L77-L92

**Comment by eliascodes** [comment]
@astroash Props with defaults seems like the best option at the moment, but if you find it starts proliferating (i.e. you end up with a component where more than 2 or 3 of the styles are prop-based), then probably worth thinking whether structuring it a different way is better.

**Comment by astroash** [comment]
@eliascodes in this particular example I cannot use props with default as the width is set in the `PrimaryButton`, and I am using a component extended off of that. I _could_ pass in a prop which overrides the initial width but this seems ridiculous...

**Comment by eliascodes** [comment]
Yes, you set the default on `PrimaryButton`, and use it on whatever extended version you are actually using.

**Comment by eliascodes** [comment]
After styling a few pages, we should start to see which styles are truly common, and which should be pulled out and collocated with the components they're actually used in.

**Comment by astroash** [comment]
_side note question..._

@eliascodes it seems we are using the 'question' label differently. I've been using it to mark questions for the PO, and using 'discussion' for dev team questions... How have you been using them?

**Comment by eliascodes** [comment]
> How have you been using them?

Arbitrarily. Let's go with your way.
