### ISSUE TITLE
Make eslint config stricter

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#297]
I'm up for us synchronising our workspace setup with either:
- everyone using the same prettier config
- no one using prettier and making our eslint config stricter

I'm currently finding myself enabling/disabling prettier dependant on what files I'm working on to avoid unnecessary difs.

**Comment by RogeredBacon** [comment]
We should have done this at the very start

**Comment by eliascodes** [comment]
Agreed. FTR, I don't use prettier. What are the eslint files for if everyone on the project was already using prettier?

**Comment by astroash** [comment]
@eliascodes I'm assuming that they started with airbnb eslint config, and have been using prettier to make it more opinionated.

Does anyone have any strong preferences either way? I am keen for everyone to be doing the same thing as this is currently a pain in the ass.

**Comment by RogeredBacon** [comment]
Yeah you're right, Zooey introduced us to prettier. I'd like to continue using prettier if possible

**Comment by eliascodes** [comment]
OK fine by me

**Comment by astroash** [comment]
I'm up for us all using prettier, but overwriting any annoyances with eslint. This could be an intermediary step whilst we make a dreamy liner config or we could continue this way.

**Comment by astroash** [comment]
It's been decided to create the worlds best eslint config and remove prettier. If any linter rules are added please relate them to this post ❤️
