### ISSUE TITLE
Naming convention for files & folders

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#305]
We seem to have a combination of kebab-case and snake_case named files & folders. Which of these are we going to use moving forward?

**Comment by eliascodes** [comment]
lol, woops this is my fault. I don't really care which, but I cast my vote arbitrarily for snake case.

**Comment by astroash** [comment]
🐍

**Comment by astroash** [comment]
Snake case makes sense, snakes eat kebabs.
