### ISSUE TITLE
Layout issues on visits page using Firefox

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#333]
I don't think this needs to be addressed in this sprint as we need to talk to PO to discuss what browsers/devices we are building for. Keeping this in an issue for future reference:

Layout for visits page is currently broken on firefox developer edition:

<img width="1022" alt="screen shot 2018-04-05 at 9 34 22 am" src="https://user-images.githubusercontent.com/14337958/38355159-b8117a7a-38c4-11e8-9fa8-5b80e0cd2ef6.png">

**Comment by astroash** [comment]
duplicate issue

**Comment by eliascodes** [comment]
same as #469
