### ISSUE TITLE
Proposed new data model

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-visitor#357]
After going back to #210 and thinking more about the schema, I propose we move to something like the following schema before we launch in earnest to avoid some complicated migrations:

<img width="1148" alt="screen shot 2018-04-09 at 23 39 41" src="https://user-images.githubusercontent.com/12719553/38526740-628d54aa-3c4f-11e8-8f7b-c429fa34bd6a.png">

IMO this better models the actual entities we are dealing with, and provides a more normalised data model.

We have had confusion around naming the "cbusiness" table, because it was actually conflating two separate concepts: the community business itself, and the community business admin. In fact it was conflating more than two concepts by including stuff about the password reset tokens and "genre" (i.e. business sector) in the same table. These are now all split out into their own tables

**Comment by eliascodes** [comment]
It comes from a database normalisation rule called 2nd normal form, which states that all columns in a table must depend ONLY on the primary key (or to put it another way, each column should be some inherent quality of the entity being described).

A business exists apart from it's geographical location (businesses can move, can exist in multiple locations), and also from it's sector (businesses can pivot, expand into other sectors, etc).

The same is true for `activity_category`, but also: it's one-to-many now, but that may not be true in future. Who's to say an activity may not belong to multiple categories?

I'm not really satisfied with the way the activity schedule is captured here. Again, a separate table may be better, but I'm happy making this change in the future via a migration once we better understand the way these things are actually used by the CBs.

**Comment by eliascodes** [comment]
Are there any more opinions or concerns about this?

**Comment by eliascodes** [comment]
Something to note: in the above model, there is no direct relationship between a visitor and a community business. This would allow in principle a single visitor account to register once and then use their QR code at multiple businesses.

However, Sonja mentioned alternative login mechanisms for visitors, including choosing from a list of registered visitors. So how would visitors who have registered but not actually selected an activity (and therefore there is no "visit" record created) be associated with one or more businesses?

**Comment by astroash** [comment]
Sounds like it would be worth having a linking table for `cb_id`'s and `visitor_id`'s. I can totally imagine the scenario where little old Gladis signs up for a visitor account at her local cb and looses her QR code. Without a link between the two cb's won't be able to find her account to resend it to her.

**Comment by RogeredBacon** [comment]
Does this mean that we're allowing any CB to see a list of all registered users, across all CBs on the Visitor Details page?

**Comment by eliascodes** [comment]
> Sounds like it would be worth having a linking table for cb_id's and visitor_id's.

Yes, good idea.

> Does this mean that we're allowing any CB to see a list of all registered users, across all CBs on the Visitor Details page?

No, even without a direct link between visitors and community businesses, we can still perform a limited visitor search via a `JOIN` on the visit table.

**Comment by eliascodes** [comment]
Updated schema: 

<img width="1151" alt="screen shot 2018-04-12 at 00 59 54" src="https://user-images.githubusercontent.com/12719553/38649192-29a7b1f4-3ded-11e8-94af-8853fbcc225e.png">

**Comment by eliascodes** [comment]
Give Sonja's latest e-mail making it clear that there seems to be a preference for having a centralised DB across the platform, I'm not going to put this on hold until at least after the workshop.

**Comment by astroash** [comment]
☝🏽Typo?

**Comment by eliascodes** [comment]
Yes, several, now corrected, thanks.

**Comment by astroash** [comment]
Closing as this has been added to the docs

**Comment by eliascodes** [comment]
No longer relevant anyway, as the database will be centralised.
