### ISSUE TITLE
Client axios requests layout

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#368]
https://github.com/TwinePlatform/DataPower/blob/18bfbc70870b47a5c429eb360fd6cb676982ac46/client/src/api/index.js#L39-L96

IMO I find the way we are storing our axios requests messy and difficult to find information from. We are using a long chain of if/else statements to match on the query obj that is passed in making the info you are looking for difficult to find. 

In this example we also seem to have a number of `post` requests on `Visitor.get`, is this just over preference of sending a body over query string?

I think this can be resolved by using more methods with clearer naming conventions.

**Comment by astroash** [comment]
@eliascodes I'll let you prioritise this one, as my temptation is to label it 🚨`priority-1`

**Comment by eliascodes** [comment]
The dependency on the new API is still here. Low-priority until the API is finalised and deployed.
