### ISSUE TITLE
CSV npm module - We use two different modules

### ISSUE THREAD

**Issue by RogeredBacon** [TwinePlatform/twine-visitor#376]
Currently we are using two different csv modules; though to be fair for two different things.

- Admin Settings CSV uses fast-csv to export to a string.
- Visits Data and Visitor Details CSV uses react-csv to export a file.

When we know more we can decide whether we want to replace react-csv entirely with fast-csv.

**Comment by eliascodes** [comment]
Only using fast-csv now
