### ISSUE TITLE
Hook up automatic deployments from master

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-visitor#417]

**Comment by eliascodes** [comment]
Done

**Comment by astroash** [comment]
Are we going to set up a staging branch?

**Comment by eliascodes** [comment]
Something like that. It's worth looking at if we can just use [heroku pipelines](https://devcenter.heroku.com/articles/pipelines) to do a similar thing for us.

I created a pipeline already but haven't set up anything else. If you want to take a look at it, go for it. You'll have to log into heroku from the twine account. Sonja sent us all the credentials a while ago.
