### ISSUE TITLE
Feedback page bug

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-visitor#468]
Via the feedback form:

### Platform
Win 10 Dell laptop: Chrome, also Firefox, also Samsung Galaxy Tab E, Chrome

### Location
Feedback screen in admin tab

### Description
> Navigate to Admin area. Click "Feedback", Twine-looking screen flashes up momentary, then screen goes white. Back button does nothing. Have to navigate back to https://twine-visitor.herokuapp.com/ and log back in to continue using the app. I am reporting this (Edward) and a user reported this too. Thanks both!

**Comment by astroash** [comment]
@eliascodes can this be closed?

**Comment by eliascodes** [comment]
No, we need to establish that whether the bug is actually fixed, the PRs were merged prematurely.

**Comment by astroash** [comment]
@eliascodes are you happy for this to be closed?

**Comment by eliascodes** [comment]
I think so.
