### ISSUE TITLE
Add support for environments via CRA

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-visitor#504]
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-development-environment-variables-in-env

This is primarily to allow dynamically changing the API URL, currently hardcoded and preventing any review/staging apps from working.

**Comment by astroash** [comment]
According to the docs this is all ready working, we were just not naming env variables correctly. They need to prefixed with `REACT_APP_`

**Comment by eliascodes** [comment]
Yeah, but we should probably also take advantage of being able to store them in `.env` files.
