### ISSUE TITLE
🐛 Visitor details page error displaying data

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#506]
![bug_visitors](https://user-images.githubusercontent.com/14337958/45686868-1dafd400-bb45-11e8-88c0-1dad44f12412.gif)

**Comment by astroash** [comment]
@eliascodes yup

**Comment by eliascodes** [comment]
It works for me locally 🤷🏼‍♂️

**Comment by astroash** [comment]
Hmmm, can you try hard resetting staging on twine-api? `/community-businessesses/me/visitors` is not setting the meta data correctly for me, which is why the `setState` function in this component is not working.

**Comment by eliascodes** [comment]
Delete your `twine-api/build` directory and try again, I remember I actually had a bit of trouble getting it to update properly.

**Comment by astroash** [comment]
Hmmm, yeah that's weird. Working now.
