### ISSUE TITLE
🐛 Password reset error

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#519]
User tried to reset their password but got multiple errors
- [no special char] too weak with no explanation why
- [with !] token has expired
- [with ?] too weak

**Comment by astroash** [comment]
Issues to fix:
- [ ]  token expires after 1 hour - extend to 1 day
- [ ] no message is displayed on what constitutes a strong password
- [ ] "?" is not considered a special character

**Comment by eliascodes** [comment]
@astroash can this be closed?
