### ISSUE TITLE
Duplicate qrcode hashes causes un-responsive visitor sign-in

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-visitor#525]
Reported by @SonjaTwine during a recent training event.

A user scanned his QRcode successfully but was then unable to complete the sign in because clicking on an activity didn't do anything.

I ultimately tracked this down to a DB error caused by the fact that this user registered multiple times with the same details, meaning the hash (used for the QRcode) generated from those details was identical. Then when the user tried to register the visit, multiple rows are returned in the subquery that grabs the user ID given the QRcode hash.

The root cause of these issues are to do with inadequate database constraints, specifically:
* Non-unique e-mails allowed during visitor sign-up
* Non-unique qr-codes allowed to be stored in the DB
* Hashes generated from non-random data

The first two issues are not a problem with the new API (see [here](https://github.com/TwinePlatform/twine-api/blob/e14547db7a1ca6a1c85dfa211905dcda8c0db511/database/migrations/sql/20180604_06_create_users.sql#L28-L53)). The latter is still an issue, but will be resolved by TwinePlatform/twine-api#188

As far as the current version of the app goes, this can be solved by: 
1. [x] removing the duplicate record in this particular case, 
2. [x] adding some random data to the hash generation.
3. [x] improving the client side error handling to offer some visual feedback

**Comment by astroash** [comment]
@eliascodes can this be closed?

**Comment by eliascodes** [comment]
Would prefer for TwinePlatform/twine-api#188 to be done first.
