### ISSUE TITLE
Visitor app: group sign in/feature to bulk-create a large number of anonymous visits

### ISSUE THREAD

**Issue by SonjaTwine** [TwinePlatform/twine-visitor#531]
On the admin part, add an additional functionality:
"Sign in a group"
On that part, the admin can simply select one of the existing Activities at that organisation, select a date and then manually enter the number of people who attended on that date.
It would then ask "Were any of these people part of this group?" and show a list of all visitors registered to this organisation, sortable and searchable by name. The admin can select multiple visitors here.

Clicking "save" will then create a number of rows/logs to the database, equivalent to the number inputted for attendees, with some of them having visitor IDs etc, and some of them "anonymous".

**Comment by astroash** [comment]
superseded by #644
