### ISSUE TITLE
Visitor app: adjustments to CB admin login screen 

### ISSUE THREAD

**Issue by SonjaTwine** [TwinePlatform/twine-visitor#533]
- keyboard currently pushes up text for "submit" and "register new account", so users may be redirected to "register" page erroneously

**Comment by eliascodes** [comment]
As per #465, CB signup will be removed from the new version of the app. User accounts will be generated manually until an automated alternative can be created.

@edwardwptc if you think there's still an issue with how the keyboard affects the elements, feel free to re-open this issue :).
