### ISSUE TITLE
Visitor app: sign in with name allowed

### ISSUE THREAD

**Issue by SonjaTwine** [TwinePlatform/twine-visitor#536]
add option next to sign in with qr code
no auto filling or name suggestions! type full name
produces an error if not existing visitor

**Comment by edwardwptc** [comment]
Okay, that looks like an excellent way to move forward with this. Very much like the idea of separating out the "created" people and the anonymous people as different creation functions. Makes it much more logical. 

Questions:

"Sign in flow
 if a user does not have a qr code with then they can select sign in with name
 if their name is a duplicate then the server will request the next piece of data we have on the user (ie if they have not supplied DOB, then we will go to postcode ect)"

Didn't you say that:
"Unique users:

    fill out sign up form
    they either need to supply an email OR a phone number"

So won't "if name is a duplicate" resolve it via the email or phone number we are requiring? 

My preference would definitely be to find some way of allowing names with extremely minimal data, but in the interests of time (and the fact our future effort to allow admins to customize mandatory signup data will inherently require us to address these questions at that stage) this looks like a really solid solution.

Very much like the "Sign in Anonymously" button idea, with a drop-down then of whatever the CB created, i.e. Anonymous Male, Anonymous Female, Anonymous Child. etc. It's not ideally what PTC or Gen originally visualised with the personal data but it absolutely is how people want to use it.

**Comment by astroash** [comment]
Great, good to hear this approach is more in line with how cbs want to use the app!

> So won't "if name is a duplicate" resolve it via the email or phone number we are requiring?

Good spot, we can do this. We already part of the sign in with DOB/post code written so if think this would be more useful as it requires less data entry we can use this approach.

**Comment by edwardwptc** [comment]
I wasn't necessarily proposing a change, just looking to understand why we'd require data sets for unique identification and then not validate with those data sets. Because obviously some CB's will find that data in some way or other, a hassle, to *have* to capture it.

If it's the best current route towards a functioning name sign up, I'm all for it. 100% 

We will want to review this in future as part of the process of allowing CB's the ability to customise signup data. Making an issue for that one shortly.

**Comment by eliascodes** [comment]
@astroash can we just close this for now and re-open once we get feedback on the feature? Otherwise it'll be hanging around "in-progress" for months.

**Comment by astroash** [comment]
Can it be moved to backlog?
