### ISSUE TITLE
Visitor app: admin needs to be able to mark an "anonymous" QR code as such

### ISSUE THREAD

**Issue by SonjaTwine** [TwinePlatform/twine-visitor#539]
on the admin part - editing a visitor account, has a small tick box that makes clear if it is not a real person but a dummy QR

**Comment by edwardwptc** [comment]
This would be solved by Aisha's proposal in #536 if we move forward with it:

Allow admins to create anonymous users as an entirely separate user process.

**Comment by astroash** [comment]
resolved with `beta-testing` #679
