### ISSUE TITLE
⚠️ instacam using deprecated api

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#547]
instacam uses URL.createObjectURL which will be deprecated from December 2018. There is a pr waiting to fix this on their repo:

see https://github.com/schmich/instascan/issues/177

supersedes #545

**Comment by Legion112** [comment]
@astroash does it fixed?

![image](https://user-images.githubusercontent.com/20613430/49642830-e8c16800-fa35-11e8-8ede-4d470077747b.png)

What should I do to fix the problem? Update instascan.min.js?

**Comment by astroash** [comment]
@Legion112 yes updating `instascan.min.js` following my instructions in the linked issue should resolve this problem. 

Support for `createObjectUrl` was dropped by chrome this week.
