### ISSUE TITLE
Visual feedback should be added to visitor signup page

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#553]
Visitor signup page can take a while to respond due to hitting a route using Postmark. It is unclear that the request is processing and users can easily hit submit again.

A loading spinner/display message should appear telling users their request in processing

**Comment by eliascodes** [comment]
Yeah, some visual feedback is probably a good idea. Possibly simpler to disable the submit button, grey it out, and change the text to "please wait" or something like that.

**Comment by aareoff** [comment]
Ok, there is a lovely Twine animated logomark in the Shared folder:

https://drive.google.com/file/d/1GB3w3MQ-1HG48IKBCAwCbJrXo62CRAiW/view?usp=sharing

I would need some modification to remove the dotty/white background but this would be perfect to indicate loading and also reinforce the Twine branding. 

 I have uploaded a loading screen design using this gif and a "Just loading..." text in the Trello card:

https://trello.com/c/zMLO19sM

**Comment by astroash** [comment]
@aareoff what was used to create the gif? Standardly load spinners would be created in css/svg animation for websites.

**Comment by aareoff** [comment]
Dunno. It's just a gif file.

**Comment by milski360** [comment]
Let's just disable the button
