### ISSUE TITLE
🐛 visit page - some graphs show todays data

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#564]
Only some graphs show visit data from today. Below this can be seen on the bar chart for last weeks visit numbers and reason for visiting. This should be consistent.

![screencapture-localhost-3000-cb-visits-2018-11-28-12_30_20](https://user-images.githubusercontent.com/14337958/49152123-c3cc4700-f309-11e8-8a08-23186be30ece.png)

**Comment by eliascodes** [comment]
Let's make it show today + previous 6 days, in both the graphs and the table.
