### ISSUE TITLE
🐛 visitor details cannot filter by age

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#565]
![visitor_details_error](https://user-images.githubusercontent.com/14337958/49153170-e3b13a00-f30c-11e8-8ae6-3a881b154bb7.gif)

returns error when using filter by age

**Comment by eliascodes** [comment]
@astroash err, sorry I hadn't noticed that you'd assigned yourself to this, have you done much work on this yet?

**Comment by astroash** [comment]
That’s okay.
