### ISSUE TITLE
🐛 homepage redirects to error page if no cookie is present

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#571]
homepage redirects to error page if no cookie is present
- onMount hits deescalate route
- deescalate returns `401`
- component forwards to 500 error page

EDIT:
- _This happens on hosted app not on local dev_
- 🙄 looks like a cors issue

**Comment by astroash** [comment]
@eliascodes it looks like our review apps will not work as we do not have the the staging app url in our cors settings. Our options are:
- review PRs locally, and staging apps on heroku pipelines
- change cors origin in `twine-api` to env vars and manually add the review app 
- write functionality for our server to build cors headers dynamically. No reference online of others doing this with hapi, but should work:
> [validate the origin header using the regex, and then you can echo the origin value in the Access-Control-Allow-Origin response header.](https://stackoverflow.com/questions/14003332/access-control-allow-origin-wildcard-subdomains-ports-and-protocols)

**Comment by eliascodes** [comment]
Before getting to that, can we just double check the problem is what we think it is? I'm not getting any CORS problems, but I am getting a `405`, and the base URL on the request is `twine-visitor-staging.herokuapp.com`, not `twine-api-staging.herokuapp.com` like it should be.

This looks like a mis-configuration of the environment variable.

**Comment by eliascodes** [comment]
My above comment has been addressed.

> write functionality for our server to build cors headers dynamically

Hapi should already do this if you supply it with wildcards. If you set
```
cors: ["https://twine-visitor-staging*.herokuapp.com"]
```
It should mirror back any domain name matching that pattern (as long as you also have the credentials config parameter set to true).

**Comment by eliascodes** [comment]
If this becomes an issue in production we should be able to configure a [reverse proxy](https://github.com/heroku/heroku-buildpack-static#proxy-backends).

**Comment by eliascodes** [comment]
I think if we have #582 this is also resolved (via the proxy option)? Does that line up with how you see it @astroash?
