### ISSUE TITLE
Redirect herokuapp domain to real domain

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-visitor#581]
To avoid CORS/cookie domain issues on launch, we should find a way to redirect requests to the old `twine-visitor.herokuapp.com` domain to the real `visitor.twine-together.com` domain.

**Comment by eliascodes** [comment]
It would be nice to be able to do this using our [current buildpack](https://elements.heroku.com/buildpacks/mars/create-react-app-buildpack), but if that's not possible, we'll have to either:
1. fork it and add our own config to it
2. create our own static server

**Comment by astroash** [comment]
Do we need a proxy if we're forcing a redirect? It will always be connecting to a subdomain.

**Comment by eliascodes** [comment]
No, and I can submit the PR without it, but IMO worth a few minutes extra work just to have the option, even if we almost certainly wont end up needing it.

**Comment by astroash** [comment]
I'm wondering if we're better off implementing a proxy, keeping this buildpack and not forwarding to hosted domain. The fact that there's no heroku solutions for redirecting on load makes me think this isnt common practice.

**Comment by eliascodes** [comment]
There's no heroku solutions because it's an application concern. There's no heroku solutions for forcing SSL either, but it's a thing lots of people do.
