### ISSUE TITLE
Reset password "Submit" button does nothing

### ISSUE THREAD

**Issue by edwardwptc** [TwinePlatform/twine-visitor#597]
Hi,

Just attempting to play around with the app/recreate the other issue maybe. 

Following Elias advice navigated to new https://visitor.twine-together.com

Here, used reset password link. Obtained email, clicked link. Landed 
![image](https://user-images.githubusercontent.com/43996813/50150560-41a2c300-02b6-11e9-9a37-b17b71178bd7.png)

Submit button doesn't do anything. Perhaps explaining why you saw people trying to reset their password a lot? 

Tried both Firefox and Chrome. 

Tried signing in with the new password, even tho submit button seems to do nothing, that doesn't work.

**Comment by edwardwptc** [comment]
Well, the reset password submit button is now working, but it still won't let me sign in - Firefox or Chrome. Login button now seems to do nothing. Shall I make a new issue?

**Comment by eliascodes** [comment]
@edwardwptc I'm seeing an error on the backend with "user does not have required role". Are you trying to log into the visitor app with the "test@email.com" account? This account cannot log into the visitor app because it is a TWINE_ADMIN account (intended for the admin dashboard only). Try logging in with another account that is a CB_ADMIN account (e.g. demo@powertochange.org.uk)

**Comment by edwardwptc** [comment]
Was using my personal Visitor app account, edwardw@powertochange.org.uk - Password1!

**Comment by edwardwptc** [comment]
Demo works fine. Weird. Have been using the above for ages - no rush tho since it's clearly working on other accounts.

**Comment by eliascodes** [comment]
Ah, I see. That account is has a role of `VOLUNTEER`, which doesn't have access to the visitor app.

There were several test accounts on the visitor app that we explicitly ignored when migrating the data, and one of them shared this e-mail, which is presumably why you can no longer log in.

**Comment by edwardwptc** [comment]
Suspected something like that. That's what I get for signing in and testing everything with that one. I'll move to using Sonja's demo one - can either remove or delete the old one.
