### ISSUE TITLE
🐛 signup bug

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#622]
A signup bug has been introduced potentially by #600 or #609 

User flow:
- sign up as new visitor
- submit form
- on success page QR code is not displayed
- on next directed to a `404` page

**Comment by astroash** [comment]
Error introduced from this commit or later:
fdddafb291b6a4a6995af1748253d82f6b97f510

Above commit cannot compile as file renaming/moving was done is separate commits

**Comment by eliascodes** [comment]
PR #623 didn't fix the 404
