### ISSUE TITLE
🔐 handle cookies for restricted/full routes

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#634]
Related to TwinePlatform/twine-api#110 

Currently we are making unnecessary api calls on routes to check users have the correct cookie.

All restricted routes call deescalate to remove full access cookies
All full routes make an api call to route with this permission, if it returns an error they will be redirected to the homepage. 

This is a less than ideal solution & needs better planning

**Comment by eliascodes** [comment]
In addition to those issues, currently the `CB_ADMIN` permissions in `restricted` include `user_details-child:read` and `user_details-child:write`. In principle, this would allow calls to, for example, `PUT /v1/community-businesses/me/visitors` by a session that does not have escalated permissions.

**Comment by astroash** [comment]
I'm still of the mindset that the current design of the permissions for `CB_ADMIN`s is over engineered. From my understanding it was done because:
- there is intention to create a Super Admin Dashboard
- we would like to have cross site cookies
- we do not want users to be able to go from the Visitor App to the Super Admin Dashboard and already be authenticated

Current status:
- Currently we do not know if/when the super admin dashboard will be created and if it's requirements will be the same as before. 
- We now have functionality for multiple users per role. If the requirements of the super admin dashboard end up wildly different than anticipated then we can create a new role for access to this site, which can be added to CB_ADMINs if they want (for small orgs) or create a new user (for bigger orgs)

Preference:
- We drop the use of restricted/full routes for CBs as this is causing unanticipated complications and deal with all restricted access to the Visitor site via protected routes as we initially had.

**Comment by astroash** [comment]
> the permissions script will be updated to remove code dealing with "restricted" mode

The changes you have listed will be added as a migration, so we don't need to change the permissions script.

Extra steps:
- remove escalate/deescalate call on client
- remove escalate/deescalate routes on server

**Comment by astroash** [comment]
As state is lost on refresh we have to options to implement this.

Desired UX:
- standard login can refresh the page and still be logged in
- escalated login refreshes the page and needs to reenter password
_(@eliascodes do you agree with this?)_

Implementation:
App wide state:
```js
{
  standardAuth: Bool,
  escalatedAuth: Bool
```
1. token is stored in local storage, on load token is added to `standardAuth` state, and added to cookies on each request
2. request is made to a random route OR specific `/authentication-check` route on load to ensure cookie is valid, if so `standardAuth` is set to true

@eliascodes do you have any thoughts? I have preference over the latter, but remember you not being keen on an auth check route previously

**Comment by eliascodes** [comment]
> token is stored in local storage, on load token is added to `standardAuth` state, and added to cookies on each request

This would mean the cookie cannot be HTTP only ☹️

So I would go with option 2 above. For simplicity, I would go with making a call to an existing route, saves you having to write a new one.

**Comment by astroash** [comment]
> For simplicity, I would go with making a call to an existing route, saves you having to write a new one.

I would really like to write a `GET /isAuthenticated?role=cb_admin`. I get it's not following the standard REST structure but it is explicit and avoids complications if scopes are moved between roles.

**Comment by eliascodes** [comment]
What about `GET /users/me/roles`? It only has `user_details-own:read`, which all users will definitely have.

**Comment by astroash** [comment]
Ok, I was thinking of checking that the request was coming from a `CB_ADMIN`. But you're suggesting that we just check they have a valid cookie. This makes sense. Just to check the overall flow would be:

1. On load check the client simply has a valid cookie for our platform. 
2. On subsequent requests the permissions of this user is checked when they hit a specific endpoint. ie their `id` is used to get `roles` > their `roles` are used to get a list of `permissions` > their `permissions` are matched against the `scope` of accessed route

Do you have any thoughts on UX for the escalated admin section? Are we happy for users to be deesacalated on page refresh?

**Comment by eliascodes** [comment]
> Just to check the overall flow would be

Yes

> Are we happy for users to be deesacalated on page refresh?

I think so
