### ISSUE TITLE
🚀 Create beta testing app

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#641]
The current changes outlined in #536 & #539 will involve a number of UX changes to the creation of users and signing up. It would be really useful if we can user test these changes before rolling out as:
- new changes will require instructions for users on how it works
- if we need to make further changes this will need to be further communicated
- people like consistency and continuous layout changes will frustrate users/negatively effect user engagement

For these reasons I think it would be useful if we setup a beta testing app where we can deploy a version of the app with new features for select CBs to test and use. This app will be connected to the live database, so all data will be saved as normal.

Steps:
- create a beta app at `twine-visitor-beta.herokuapp.com` with the new feature
- details of feature changes given to testing CB
- after a week of use request feedback of new feature from testing CB
- when the app is out of `beta` above URL will redirect to `visitor.twine-together.com` 

@eliascodes @edwardwptc it would be useful to hear your thoughts on this. Particularly:
- do we think this would be useful?
- do we have any CBs who would be willing to test this feature AND provide feedback
- how would we like this feedback to be given?
- what type of feedback would we like?

**Comment by eliascodes** [comment]
@astroash I agree with this idea.

> create a beta app at twine-visitor-beta.herokuapp.com with the new feature

Think we'd want to make it `visitor-beta.twine-together.com`, no? Avoids cookie worries.

@edwardwptc 

> Re: Types of feedback

All the stuff you listed sounds good!

**Comment by astroash** [comment]
> Avoids cookie worries.

We can do this anyway with the proxy you set up. Would look more _official_ on a subdomain though.

**Comment by astroash** [comment]
On second thought, we also need a beta-testing branch for the api. I believe we only discussed this for the visitor-app, however new features will involve api changes which may cause undesired side effects for client apps

TwinePlatform/twine-api#318

**Comment by astroash** [comment]
Prep for beta-testing:

- [ ] "sign in with name" #653  and "anon user creation" #654 PRs tested and merged
- [ ] setup heroku app for `beta-testing` branch
- [ ] setup dns subdomain for `visitor-beta.twine-together.com`
- [ ] create feedback template/user testing script

**Comment by eliascodes** [comment]
### Beta testing questions for users
- When arriving on the sign in page (with the webcam view and sign in form) 
  - is it clear what you need to do?
  - is it clear that there are two alternatives for how to sign in?
- Did you have any difficulties when trying to sign in with name?
- If anything didn't work in the way you expected during your usage of the app, please provide details below
- While using the app, were you ever unsure of what to do next? If so, please describe this
- Signing in with name only works if there is an exact match. Is this workable for your use case?

@astroash @edwardwptc if there are more questions you think would be useful (or if you'd like to suggest changes to the above), please let me know.
