### ISSUE TITLE
Visitor App Additional Feature: Research into signup demographic/postcode data

### ISSUE THREAD

**Issue by edwardwptc** [TwinePlatform/twine-visitor#643]
Admins would like the ability to choose which data appears on the sign up screen.

Optional: Admins would like the ability to choose which data is used to validate duplicate users.

If Aisha's planning in #536 where we simply look at all the data we have and validate from that as an automatic process, the optional process isn't necessary. 

Data Fields CB's have stated are useful:
Name
Year of Birth
Gender
Email
Phone

Postcode (Full, S63 0DY) 

Potentially Disability (Pull categories from PTC literature (which I wrote, haha))
Potentially Ethnicity (From Census data)

Both potentials above were suggestions from Sonja - I haven't yet interacted with those CB's so can't say for certain. See #551 for discussion about how these fields should work/look. Summary: Default to "prefer not to say" rather than saying "Optional". 

Suggestion:
Element of the admin area where each of the above data sets are listed, name is default always on and can't be changed. Everything else gets a checkbox. If boxes are checked, these appear on user signup.

Questions to be answered (not necessary to make the above work):
Will want to be sure that existing users won't cause problems if these metrics are changed midway, so if a CB takes on a project involving tracking people's postcode where previously they didn't if they enable it;
Does it just accept "Michael Smith" just fine?
Does it prompt "Michael Smith" to now give us his postcode? 

Will need to discuss with CB's/focus group.

**Comment by edwardwptc** [comment]
Adding potential additional optional field based on user suggestion: Emergency Contact Number.

This would also be appropriate for the volunteer app, if we are working towards data capture on both apps being symmetrical.

**Comment by astroash** [comment]
### Twine team Scoping

| (1 = low probability; 10 = high probability)               | Total | 
| --------                                                   | ----- | 
| Sales: Will this contribute to new users?                  | 7     | 
| Retention: Will it improve user retention?                 | 7     | 
| Operations: Will it improve our operational effectiveness? | 7     | 
| Development: How much effort will this be to develop?      | - 7     | 
| Average                                                    | 14     |

**Comment by milski360** [comment]
We'll need to explore the user flow, to enable Devs to give more accurate scope of work.

**Comment by milski360** [comment]
We will develop a spec for this. Requires design. As a stop gap we will add a 'postcode' field as mandatory) followed by other demographic fields.

**Comment by milski360** [comment]
Release = minor (Devs to release); validation required on postcode

**Comment by astroash** [comment]
@milski360 can this issue be closed or is it being used to track the suggested actions above https://github.com/TwinePlatform/twine-visitor/issues/643#issuecomment-514672142

**Comment by milski360** [comment]
@astroash Do you know the status of the actions listed on this thread? These include:

- Adding postcode field as mandatory - requires validation on postcode 

- Adding Age and Gender fields as optional 

If they've been done then this issue can be closed.

**Comment by astroash** [comment]
Post code is a mandatory sign up field on visitor and volunteer app. Gender and age are both optional. 

Above you mention:
> We will develop a spec for this. Requires design. As a stop gap we will add a 'postcode' field as mandatory) followed by other demographic fields.

I can't remember what the other spec related to this issue are so wanted to clarify before closing.

**Comment by milski360** [comment]
Ah I see. Other spec if listed in Edward's comments here: https://trello.com/c/kZsSYdCM. Essentially monitoring disability etc. We can revisit this as and when required - above is more pressing. Happy to close this card.
