### ISSUE TITLE
🐛 ✅ Use fireEvent to update values

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#647]
Tests are currently updating component values by accessing elements directly eg

```
fullName.value = visitor.name;
```

Turns out this doesn't actually work, hence a lot of test bugs we've been having recently. Values should be updated using fireEvent options object eg:

```
fireEvent.change(fullname, { target: { value: visitor.name } });
```

https://testing-library.com/docs/example-input-event

**Comment by eliasmalik** [comment]
This isn't done yet, there's still loads of places with the old style API.
