### ISSUE TITLE
🛀🏽 Suggested file (re)-structure

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#652]
Our current file structure does not lend itself to easily separating out pages into individual components. This is because any components that are pulled out of the `PageComponent` file end up in a components folder shared with all other non-page components. 

Suggestion:
- Each page is its own folder
- page components live in index.js
- pulled out 'page specific' components live in page folder
- `/components` renamed to `/sharedComponents`

edit:

On second thought, can be used **only** on pages that have separated out components and work with our current file structure.

**Comment by eliascodes** [comment]
Yep, this sounds good to me.
