### ISSUE TITLE
🐛 mismatch in visit data/exported data on visits page

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#687]
> Exported data does not match the data you filtered for or are viewing.
Data is missing in the xls in terms of fields and complete list of data. 
These fields are blank: Visit ID	Full Name	Year of Birth	Activity	Visit Date
Only returns 20 rows despite the table containing 14 pages of data

https://github.com/TwinePlatform/hq/issues/55

**Comment by eliascodes** [comment]
This was fixed in #673 and deployed in #665
