### ISSUE TITLE
<13 Years Old Registration "2.0" - User Insight/Request

### ISSUE THREAD

**Issue by edwardwptc** [TwinePlatform/twine-visitor#701]
Hi both,

I've had an extensive conversation with Rob (CEO - Focus Group member) about the way they would like to use the visitor app. This focused on the many youth groups they have, which they currently log via paper registration sheets. One of their key focuses is on using Twine to digitize these logs. Currently, we prevent this. 

I will be speaking with PTC's GDPR consultant shortly to confirm that we are able to, with consent, store children's name, age, gender and parents contact details, in the same way that the user org currently does for paper/excel storage.

Two ideas about how we can register under 13's from the admin end but prevent normal user access from registering these people (because it is the organisation that requires consent, so it must be an admin doing it). 

1. Twine to fully duplicate the "Sign up" form within the admin menu, except within this duplicate, "Year of birth" would be unlocked for any age. Selecting any age that would make the user under 13, an additional popup would appear which reads "You must gain parental consent to store this user's data on the Twine system. Please tick to confirm you have this consent." and a tickbox that must be ticked to register the user. 

Once done the user would behave like any other - be a registered visitor, have a qr code, signin as normal etc.

2. On the user Sign In page (as normal), all years of birth are displayed. If a year is chosen that would make that user under 13, a popup appears that says "Registering a visitor account under 13 years of age can only be done by an administrator. Please enter your admin code. By doing so you confirm you have the parental consent needed to lawfully store data for this child." and we generate a single code visible from somewhere in the admin side that staff will know to use for this purpose. 

My initial thoughts are that 1. probably is easier, but what do I know about dev work? :P However it is logically better as it avoids overcomplicating the actual visitor sign-in experience potentially. The only user flow that involves registering children 100% has to be by staff who state there is consent anyway, so having it admin gated makes a lot of sense. 

Thoughts/Feedback appreciated. Depending on how functional it is for us, it may be high priority (after dashboard ofc). Work on the basis we are legally ok to do this - I will be ensuring this is the case - and if not, I'll be addressing that here.

**Comment by astroash** [comment]
Option 1 is fairly easy to implement. My initial thoughts:

1. Is this something that we want to deploy to production or to the beta-testing app

2. Are we leaving cbs in charge of parental consent or do we want to provide a form for them to print as part of this flow? Or email parents for consent (more complicated)

3. Are we getting to the point where we want to the point where cbs can personalize their admin dashboard so that not all options are visible eg create anon & sign up minor. Or can we rearrange dashboard pages so they are nested under categories.

**Comment by edwardwptc** [comment]
Cool! I had a feeling it'd be the easier option. 

1. I'd think so, yes. The likelihood that other orgs may end up wanting to use it is high, I think. Many CB's have services for young people. 

2. I'll have to speak to our GDPR dude to confirm this but I'd say yes. They already should be getting consent even to papercapture data about <13's so if they want to use our system they just need to update their processes to reference our system and our use of their data. Maybe we'll have a set paragraph to go into their existing forms or something like that, but my understanding is that it isn't substantially our process to manage. 

3. Possibly, for neatness, I'd say either, whichever is easiest for us to implement. Under account settings you could tickbox different elements like the above proposed, or the emoji feedback faces. I think the customization takes us further towards our eventual goal of having some of those elements be customizable anyway, i.e. a tickbox on the admin side that removes the emoji faces for orgs that don't want them "cluttering" the main screen.

**Comment by astroash** [comment]
From your knowledge you have an estimate for the priority of this feature?

**Comment by edwardwptc** [comment]
TLC has a substantial amount of younger people who they want to register asap, tho they are still in the early stages of deployment of both apps. It's a high priority as using Twine to register young people is a dealbreaker for them. Unless it's a substantial amount of work I'd say it's right behind the admin dashboard.

So yes - depends on the time estimate involved in the creation of option 1. Obviously, before we assign priority I need to speak to our GDPR person.

**Comment by edwardwptc** [comment]
Transcribing my email chain with PTC's Director of Finance here: 

Sent from myself to Alex F:

I used to be the GDPR officer at my old workplace (prior to it coming in to force) and my understanding is that we would be fine where:

   1,  Community businesses state that parental consent has been obtained for under 13's. (It's not our responsibility to do this as we are a data processor, not a controller.)
    2. We don't market to children or sell their data in any way.
   3.  The Twine database meets or exceeds industry standard security for the storage of personal data. 

Essentially, we are a service being contracted to perform data processing services by a community business, which happens to include processing data for people of all ages. If that CB wants to process children's data, that's fine, and it's their decision. We will have a checkbox when registering anyone under 13 that says "In order to process data on children under 13, parental consent is required. Please tick this box to confirm you have obtained parental consent to process this child's data."

That way each individual user who would require this consent will specifically be marked as having done so.
Obviously, in our terms and conditions for Twine use we indicate all the appropriate provisions for the GDPR about access and right to object and so forth, and outline the fact we won't be using this for marketing or anything else.

I'm looking for a second pair of eyes to the above; have I missed anything, are my conclusions wrong, do we need more substantial legal consent etc.

**Comment by edwardwptc** [comment]
Alex F's reply:

"I think that you have made a perfect summary of our position. 

I assume that someone at the CB needs to set up the young person on Twine, so they, the CB, not the young person, sees the consent check box?

The one thought I had was that whilst it is fine for us to rely on the CB’s confirmation that parental consent has been obtained, perhaps we should recommend that the CB gets this consent in writing?  I assume that they will be far more attuned to young people’s GDPR consent than we are and will already being doing this?"

**Comment by edwardwptc** [comment]
I can confirm that the current proposal above to have creation of <13's gated behind the admin password meets Alex's requirement that it is CB staff who are indicating that consent has been obtained. 

The CB that specifically requested this already captures written consent from parents. It would simply be modified to indicate CB's use of Twine. I will make it a formal point in training regarding <13's that written consent be captured. I have confirmed this with Alex.

I personally feel this is a substantial enough confirmation of my above reasoning that we can move forward with this feature. @milski360 I'd appreciate a second read over this just to confirm please.

**Comment by milski360** [comment]
This sounds reasonable to me. Where will this sit in the development pipeline though, and how easy is it to implement? I thought we had previously agreed a principle that we would prioritise developments which impacted on tens and hundreds of CBs over those requested by just one? In which case the dashboard is clearly a higher priority, though I can see how this development might be used by others.

**Comment by edwardwptc** [comment]
I imagined this as being immediately after the dashboard, as Ash said above this would be "fairly easy", unless there are blockers which prevent dashboard work in which case work on this would be ideal. 

I'm definitely on board with priority is based on bigger impact, but on the microscale, if we don't make it work for individuals (at least where we can because the dev work isn't substantial) we won't ever reach tens and hundreds of CB's anyway. 

Added to that, Rob is one of the most engaged users we have so far, from the very genesis of the idea for the focus group he's given us a substantial about of time and information. If we are viewing this assistance as an asset, we definitely don't want him to burn out or get jaded by us failing to sort out a key feature (in his view). 

Not to turn this into a lecture either (sorry) but last year we did have a feature request of this nature, just from a different CB who then fell off (change of responsible staff, since re-engaged but not very) so it's definitely not just this one org.

**Comment by milski360** [comment]
Great, thanks for explaining. Let's add it to the pipeline then.

**Comment by astroash** [comment]
| (1 = low probability; 10 = high probability)               | Total | 
| --------                                                   | ----- | 
| Sales: Will this contribute to new users?                  | 7     | 
| Retention: Will it improve user retention?                 | 7     | 
| Operations: Will it improve our operational effectiveness? | 2     | 
| Development: How much effort will this be to develop?      | 5     |

**Comment by aareoff** [comment]
@edwardwptc @astroash where are we at this this feature? 

I'm not in a position to advise on the GDPR/legal aspects of under 13 signups but I think it would be good if we could get this requirement together into an User Story (sorry if it already existings) and requirements so we can move forwards to looking at some initial wireframes to incorporate the features/forms/flow with a view to prototyping it with the focus group.

**Comment by edwardwptc** [comment]
Doing so now, I don't know about focus group prototyping. I think we'd just take it to the originator org since they were the people who requested it. We don't have any other visitor app focus group members due to very low visitor app user count.

**Comment by aareoff** [comment]
There may well still be a lot of value in taking it to the originator org – do you think they would be able to provide valuable feedback on our prototype @edwardwptc ?

**Comment by edwardwptc** [comment]
Draft user story under new format now on Trello card.

**Comment by aareoff** [comment]
I have done a first version of the u13 sign-up flow which also includes a new "create new visitor" in place of the "create anon user" but which also includes a link to do that too...

These are the wireframes that apply:

https://balsamiq.cloud/sy3chtp/paw5i7h/rDD06

https://balsamiq.cloud/sy3chtp/paw5i7h/rE5B9

https://balsamiq.cloud/sy3chtp/paw5i7h/rEFAB

**Comment by astroash** [comment]
> but which also includes a link to do that too...

@aareoff where's the link to the anonymous user creation page?

**Comment by edwardwptc** [comment]
@aareoff  

Few comments.
Implementing date of birth sort of is necessary I can see to capture specific dates as YoB as you say is not fine enough, but I'd rather there be another way to avoid having a category of people with YoB and a different category with DoB, with the exception maybe of only <13's having DoB and once they are 13 the system automatically converts that into a year and leaves them as a normal visitor (if they even continue to visit at all etc).

Duplicating "Create a visitor" isn't appropriate here, at all. The idea was to duplicate the data input fields, but actually calling it "Create a visitor" suggests to CB admins that they can just go into the admin area and sign up whoever they want, which isn't what we currently believe is GDPR compliant. This is why the admin is specifically signing up A. Anonymous People (They can do whatever they want with anonymous people) and B. Under <13's who need specific parental consent. 

I'm going to speak to our new GDPR person hopefully this week in order to clarify this. If they actually do have the legal right to sign up whoever they want, then we can leave it like this. 

The "how we use personal data" bit on the right hand side of the sign up can be left, I think, for reference, including the email section. A parent's email may be included and therefore if this process is done in their presence, or digitizing existing forms, we can only benefit CB's from having a way for such profiles to be added to mailing lists. That said we still 100% need to remove the SMS checkbox, it's not relevant and it's confusing.

**Comment by Shanozd** [comment]
@edwardwptc just a quick question. For our other user story where 'facilitators' log attendance at a specific session, I'm wondering how the visitor data could be put in initially? Should all attendees sign up individually, or as part of their registration could their data be put into the visitor app? hmm, I wonder if there is a new flow here.

When it comes to GDPR we'd probably need user consent to store personally-identifying info. Would that fit with @aareoff's flow and the under 13's as well? It could just be a change to the consent wording?

**Comment by edwardwptc** [comment]
In terms of facilitators and sessional-based logging (if that ever becomes a thing) the intention there is to mark who is at a session from the existing bank of people but to have "add a new visitor" and then for that staff member to go and obtain those details and consent in person on a 1:1 basis. By nature the "I am leading this group. I know everyone here, except for that person." so at some stage the staff member has to physically approach the person and capture the information about them. The app could be made to easily feature a signup function inside this where the tablet is handed to the visitor with a "Could you give us some details?" type of way. 

(Though there is a bigger conversation there to have about essential details. That's a longer story and separate - if visitors only want to give a name, don't have an email address or a phone number, we need to enable that for severely deprived communities.)

The sidenote here is if it's essentially OK for a CB to put visitor data whereever they want so long as they are the controller and they hand it to a processor (like putting visitor data into google drive, for instance? They don't exactly get consent for that...) then sure, visitor data can be input by any CB for whatever reason they like. I've got a meeting with PtC's GDPR person in 25mins :) 

Re: Your final note: We presume there is consent to store personal data, but technically for <13's it's parental consent, so that should be fine.

**Comment by Shanozd** [comment]
@edwardwptc thanks!
I wonder if user flows for both <13's and attendance logging would help? Anyway something we can discuss

**Comment by aareoff** [comment]
@edwardwptc Ok let me know what comes out of your review and advice from your GDPR people and we'll move on with the user flow from there.

**Comment by astroash** [comment]
See US for requirements
