### ISSUE TITLE
QA: Confirm Role Feature

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-visitor#707]
Related to #704 and TwinePlatform/twine-api#371
### `visitor-app`
* Case 1: **SUCCESS** - `VOLUNTEER` user adds a second role (`VISITOR`)
  - [x] step 1
  * populate DB with `VOLUNTEER` user with e-mail that you have access to
  * sign up to visitor app with email used as a `VOLUNTEER`
  * ~~respond to confirmation email~~
  * ~~webpage will tell you its a success~~
  - [x] step 2
  * go to email and click on link (domain will need to be replaced with `localhost:3000`)
  * confirm your email creation
  * check you have an email with your QR code
* [x] Case 2: **FAILURE** - `VOLUNTEER_ADMIN` user adds a second role (`VISITOR`)
  * populate DB with `VOLUNTEER_ADMIN` user with e-mail that you have access to
  * sign up to visitor app with email used as a `VOLUNTEER`
  * webpage will tell you its a failure (see new PR)
* [x] Case 3: **FAILURE** - `VOLUNTEER` user from another CB adds a second role (`VISITOR`)
  * populate DB with `VOLUNTEER` user at another CB with e-mail that you have access to
  * sign up to visitor app with email used as a `VOLUNTEER`
  * webpage will tell you its a failure

### `volunteer-app`
* [x] Case 1: **SUCCESS** - `VISITOR` user adds a second role (`VOLUNTEER`)
  * reset the DB, insert demo data
  * populate DB with `VISITOR` user with e-mail that you have access to
  * sign up to volunteer app with email used as a `VISITOR`
  * respond to confirmation email
  * webpage will redirect you to password reset to set your password
  * reset password
  * log in to volunteer app
* [x] Case 2: **FAILURE** - `VISITOR` user adds a second role (`VOLUNTEER_ADMIN`)
  * sign up to volunteer app with email used as a `VISITOR` & a `VOLUNTEER_ADMIN` code
  * webpage will tell you its a failure
* [x] Case 3: **FAILURE** - `VISITOR` user from another CB adds a second role (`VOLUNTEER`)
  * populate DB with `VISITOR` user at another CB with e-mail that you have access to
  * sign up to volunteer app with email used as a `VISITOR`
  * webpage will tell you its a failure

### security
* [x] Case 1: token already used
  * go to confirm page with a used token will give you an error message (URL path of the form `/confirm-role/USEDTOKENGOESHERE?role=...`
* [x] Case 2: malformed query string
  * go to confirm page with bad/edited query string will give you an error message

**Comment by mandsmandsmands** [comment]
1. SUCCESS - VOLUNTEER user adds a second role (VISITOR)
a) Error msg is seen when signing up as a new visitor: "Email Address: Email is associated to a volunteer, please see email confirmation to create visitor account" - PASS
b) Email entitled: "Set up a new visitor role for an existing volunteer" - PASS
c) Clicking on link in email - FAIL - 404 page not found
We are sorry, but the page you a looking for does not exist.

**Comment by astroash** [comment]
> c) Clicking on link in email - FAIL - 404 page not found
We are sorry, but the page you a looking for does not exist.

The domain needs changing in the email link. `visitor.twine-together.com` needs replacing with `localhost:3000`. This is because the changes are not deployed yet and must be tested locally with a local database.

**Comment by eliascodes** [comment]
> The domain needs changing in the email link. visitor.twine-together.com needs replacing with localhost:3000. This is because the changes are not deployed yet and must be tested locally with a local database.

We're testing on staging, not locally, and I already updated the link in the template

**Comment by mandsmandsmands** [comment]
**volunteer-app
  Case 1: SUCCESS - VISITOR user adds a second role (VOLUNTEER)**
reset the DB, insert demo data - DONE by Dev
populate DB with VISITOR user with e-mail that you have access to - DONE by dev

a) Sign up to volunteer app with email used as a VISITOR. Click register here on volunteer app - PASS
b) Fill out registration details and submit - We see an error message dialog as expected "Registration unsuccessful - email associated to a visitor, please see email confirmation to create volunteer account". Click ok button - PASS
**c) go to email and find email FAIL 
Email subject: "Set up a new visitor role for an existing volunteer" - need template needs to be updated to say "Set up a new volunteer role for an existing visitor"
Grey hading of email "Twine Visitor App" to be changed to "Twine Volunteer App"**
d) respond to confirmation email - click button PASS
e) webpage will redirect you to password reset to set your password - PASS
**f) reset password click submit - Invalid token. Request another reset email. - FAIL - Elias to investigate**
- - - - - - - - 
g) log in to volunteer app - 
h) log in as admin and view volunteer in list and details -

**Comment by eliascodes** [comment]
@astroash is taking over cases 1, 2 and 3 of the volunteer app test cases.

Note:
> Grey hading of email "Twine Visitor App" to be changed to "Twine Volunteer App"

This is already done.

**Comment by mandsmandsmands** [comment]
**volunteer-app
 Case 1: SUCCESS - VISITOR user adds a second role (VOLUNTEER)**
reset the DB, insert demo data - DONE by Dev
populate DB with VISITOR user with e-mail that you have access to - DONE by dev

a) Sign up to volunteer app with email used as a VISITOR. Click register here on volunteer app - PASS
b) Fill out registration details and submit - We see an error message dialog as expected "Registration unsuccessful - email associated to a visitor, please see email confirmation to create volunteer account". Click ok button - PASS
c_i) go to email and find email - PASS
c_ii)Email subject: "Set up a new visitor role for an existing volunteer" - updated to say "Set up a new role for your user account" - PASS
c_iii)Grey heading of email "Twine Visitor App" to be changed to "Twine Volunteer App" - changed - PASS
d) respond to confirmation email - click button PASS
e) webpage will redirect you to password reset to set your password - PASS
f) reset password click submit - PASS
g) log in to volunteer app - PASS
h) log in as admin and view volunteer in list and details - PASS 
i) As admin, create log on behalf of a new volunteer - PASS

**Comment by astroash** [comment]
> visitor-app
Case 2: FAILURE - VOLUNTEER_ADMIN user adds a second role (VISITOR)
a) sign up to visitor app with email used as a VOLUNTEER - PASS
b) webpage will tell you its a failure (see new PR) - PASS - Error msg is shown "Email Address: User with this e-mail already registered at another Community Business"

This test should not have returned this error message. Was the database reset in between test cases?

**Comment by mandsmandsmands** [comment]
**volunteer-app
Case 2: FAILURE - VISITOR user adds a second role (VOLUNTEER_ADMIN)**
sign up to volunteer app with email used as a VISITOR & a VOLUNTEER_ADMIN code - DB reset done by Dev
webpage will tell you its a failure
a) Click register here on volunteer app with - PASS
b) Fill out registration details with admin code and submit - Error msg is shown "Registration Unsuccessful: User with this e-mail already registered"

**Comment by mandsmandsmands** [comment]
**volunteer -app
Case 3: FAILURE - VISITOR user from another CB adds a second role (VOLUNTEER)**
populate DB with VISITOR user at another CB with e-mail that you have access to
sign up to volunteer app with email used as a VISITOR
webpage will tell you its a failure
a) Click register here on volunteer app 
b) Fill out registration details with that Visitor user and submit - Error msg received - ""Registration Unsuccessful: User with this e-mail already registered at another Community Business"

**Comment by mandsmandsmands** [comment]
RETEST REQUIRED:

**visitor-app
Case 2: FAILURE - VOLUNTEER_ADMIN user adds a second role (VISITOR)**
a) sign up to visitor app with email used as a VOLUNTEER - PASS
b) webpage will tell you its a failure (see new PR) - PASS - Error msg is shown "User with this e-mail already registered"
